### ISSUE TITLE
Target [GuzzleHttp\ClientInterface] is not instantiable.

### ISSUE THREAD

**Issue by fajarsulaksono** [rick20/ppob#2]
Ketemu error lagi ini gan, coba besok saya kulik2 kali bisa bantu :

`Target [GuzzleHttp\ClientInterface] is not instantiable.`

Platform latest laravel 5.8.32

**Comment by rick20** [comment]
klo boleh tau pake provider apa gan? memang saat ini utk provider selain mobile pulsa sy blom test menyeluruh nih gan, blom pernah pake provider lain soalnya hehehe

dgn senang hati gan klo bersedia bantu ...thank you yah gan

**Comment by fajarsulaksono** [comment]
pake mobilepulsa gan, tapi masih coba2 jg ini, masi pake yg development belum production

**Comment by rick20** [comment]
ooh ok2...packagenya udh pake yg versi 0.1.9 gan?

**Comment by fajarsulaksono** [comment]
Iya gan udah pake yg 0.1.9

![Screen Shot 2019-08-22 at 08 59 15](https://user-images.githubusercontent.com/202346/63480269-67bed980-c4bb-11e9-806d-d40679aa293d.png)
