### ISSUE TITLE
Untuk instalasi apakah perlu config di app.php & di controllernya perlu declare facade nya ?

### ISSUE THREAD

**Issue by fajarsulaksono** [rick20/ppob#3]
Berikut langkah instalasi saya gan :

![Screen Shot 2019-08-22 at 09 02 39](https://user-images.githubusercontent.com/202346/63480372-e0be3100-c4bb-11e9-8589-9a38e5af1fc4.png)

Kemudian di controllernya :
![Screen Shot 2019-08-22 at 09 03 06](https://user-images.githubusercontent.com/202346/63480390-eb78c600-c4bb-11e9-987a-68cfdcd2f1f4.png)

**Comment by rick20** [comment]
Oh iya betul mas...facade nya perlu di daftarin di config/app.php

Product yg dicoba apa mas? Sy ada project yg pakai mobilepulsa jg sejauh ini utk pulsa, paketdata dan token PLN aman gan.

Errornya spt yg di issue #2 yah gan?

**Comment by fajarsulaksono** [comment]
Iya betul gan error yg interface GuzzleHttp

**Comment by rick20** [comment]
Bisa dicoba composer update lg yah gan...barusan ane update versi 0.1.10.

**Comment by fajarsulaksono** [comment]
Ok gan saya coba dulu `composer update`

**Comment by rick20** [comment]
Bentar gan...packagist nya msh salah

**Comment by rick20** [comment]
Bisa dicoba lg yah gan

**Comment by fajarsulaksono** [comment]
Mantap gan, udah bisa ini `$balance = PPOB::balance();`
![Screen Shot 2019-08-22 at 12 22 49](https://user-images.githubusercontent.com/202346/63488043-b2e6e580-c4d7-11e9-8c67-b218ba3fdd5b.png)
