### ISSUE TITLE
Support untuk Laravel 7

### ISSUE THREAD

**Issue by fajarsulaksono** [rick20/ppob#4]
Halo mas,
Apakah ada rencana untuk pengembangan support ke laravel 7 ?

**Comment by rick20** [comment]
@fajarsulaksono halo mas, oh iya, sy coba update composer nya yah mas

**Comment by fajarsulaksono** [comment]
baik mas terima kasih

**Comment by rick20** [comment]
@fajarsulaksono bisa di coba lg yah mas. tq

**Comment by fajarsulaksono** [comment]
Baik mas terima kasih saya coba2 dulu
